- name: My favorite settings
  hosts: localhost,
  tasks:
    - name: ensure zsh is installed
      become: true
      package:
        name: zsh
        state: present
    - name: find zsh path
      command: which zsh
      register: zsh_path
      changed_when: false    
    - name: add zsh to /etc/shells
      become: true
      lineinfile:
        path: /etc/shells
        line: "{{ zsh_path.stdout }}"   
    - name: set default shell
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: "{{ zsh_path.stdout }}"
    - name: clone oh-my-zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
        depth: 1   
    - name: edit .zshrc
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.zshrc"
        content: |
          export ZSH="$HOME/.oh-my-zsh"
          ZSH_THEME="robbyrussell"
          plugins=(git)
          source $ZSH/oh-my-zsh.sh
    - name: Set Homebrew paths
      ansible.builtin.set_fact:
        brew_bin: >-
          {{
            '/opt/homebrew/bin/brew'
            if ansible_system == 'Darwin'
            else '/home/linuxbrew/.linuxbrew/bin/brew'
          }}
    - name: Install Homebrew
      ansible.builtin.shell: |
        /bin/bash -c \
        "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      environment:
        NONINTERACTIVE: "1"
      args:
        creates: "{{ brew_bin }}"
    - name: Add Homebrew shellenv on macOS
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.zprofile"
        line: 'eval "$({{ brew_bin }} shellenv)"'
        create: true
    - name: Install packages with brew
      community.general.homebrew:
        name:
          - helix
          - zellij
          - node
          - gh
        state: present
        path: "{{ brew_bin }}"
    - name: Install packages with npm
      community.general.npm:
        name: opencommit
        global: yes
        state: present
